
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:7.2.2")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21")
    }
}

plugins {
    // Add the dependency for the Google services Gradle plugin
    // id("com.google.gms.google-services") version "4.4.1" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
    }
	buildscript {
		extra.set("ndkSideBySideVersion", "21.4.7075529")
		extra.set("cmakeVersion", "3.17.3+")
		extra.set("kotlinVersion", "1.6.21")
	}
}

tasks {
    wrapper {
        gradleVersion = "7.5"
        distributionType = Wrapper.DistributionType.ALL
    }

    register<Delete>("clean") {
		// Clean the build artifacts generated by the Gradle build system only, but keep the buildDir
        rootProject.buildDir.listFiles { _, name ->
            name == "intermediates" || name == "kotlin"
        }?.let {
            delete(it.toSet())
        }
    }

    register<Delete>("cleanAll") {
        dependsOn("clean")
    }
}

