#define ACTIVE_STDRANDOMIZER
//#define ACTIVE_HISCORE
#define ACTIVE_SERIALIZEGAMESTATE
#define ACTIVE_PRELOADER
#define ACTIVE_PRELOADER_ASYNC
#define ACTIVE_POOL

#define ACTIVE_CONSOLECOMMAND
#define ACTIVE_HANDLECURSORVISIBILITY
#define ACTIVE_SDLMAPPINGJOYSTICK_DB
#define ACTIVE_SPLASHUI

//#define ACTIVE_MISSIONDIALOG
//#define ACTIVE_TOUCHTIPS
#define ACTIVE_GAMELOGLEVEL
//#define GAMELOGLEVEL_MINIMAL LOG_NONE
#define GAMELOGLEVEL_MINIMAL LOG_ERROR
#define GAMELOGLEVEL_DEFAULT LOG_INFO

//#define DUMP_COMPONENTTEMPLATES
//#define DUMP_ATTRIBUTES
//#define DUMP_SCENE_BEFORERESET
//#define DUMP_SCENE_AFTERRESET
//#define DUMP_LEVELGRAPH
//#define DUMP_UI
//#define DUMP_RESOURCES
//#define DUMP_SIMLATE_FIRST100LEVELS

#define MAXOBJECTIVES 5
#define DIFFICULTYLEVELTHRESHOLD 20

//#define ACTIVE_RESTORESTARSONRETRY

#define MAX_ADDINGSTARS 4
#define EARNSTAR_MAXAUTHORIZEDSTARS 6
//#define EARNSTAR_DELAY 86400 // 24h
//#define EARNSTAR_DELAY 43200 // 12h
#define EARNSTAR_DELAY 21600 // 6h
//#define EARNSTAR_DELAY 7200 // 2h
//#define EARNSTAR_DELAY 600   // 10min
//#define EARNSTAR_DELAY 2   // 2sec

#ifndef __ANDROID__

    #ifdef _DEBUG
//        #define ACTIVE_GAMELOOPTESTING
        #define ACTIVE_TIPS

//        #ifdef ACTIVE_SERIALIZEGAMESTATE
//            #undef ACTIVE_SERIALIZEGAMESTATE
//        #endif
    #endif

    #define ACTIVE_CINEMATICS
    //#define ACTIVE_CINEMATICS_BUTTONONSCENE
#endif

#ifdef ACTIVE_GAMELOOPTESTING

    #define TESTMODE

    #ifdef ACTIVE_SERIALIZEGAMESTATE
        #undef ACTIVE_SERIALIZEGAMESTATE
    #endif

#endif

#ifdef TESTMODE
//    #ifndef ACTIVE_TOUCHTIPS
//        #define ACTIVE_TOUCHTIPS
//    #endif
    #ifndef ACTIVE_TESTMODE
        #define ACTIVE_TESTMODE
    #endif
    #define TESTMODE_STARTZONE  1
#endif

#define DEMOMODE_MAXZONE 3

