name: CMake + Gradle Build (Windows, Linux, Android)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: Release
            target: windows

          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: Release
            target: linux

          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
            build_type: Release
            target: linux

          - os: ubuntu-latest
            build_type: Release
            target: android

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Cache Linux dependencies
      if: matrix.os == 'ubuntu-latest' && matrix.target == 'linux'
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/apt-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Setup Linux dependencies
      if: matrix.os == 'ubuntu-latest' && matrix.target == 'linux'
      run: |
        sudo apt update
        dependencies="libglu1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev \
                      libxrandr-dev libxrender-dev libxss-dev libxxf86vm-dev \
                      libasound2-dev libpulse-dev libibus-1.0-dev \
                      libdbus-1-dev libreadline6-dev libssl-dev libudev-dev"
        for dep in $dependencies; do
          dpkg -s $dep &>/dev/null || sudo apt install -y --no-install-recommends $dep
        done
        
    - name: Cache Chocolatey packages
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v3
      with:
        path: C:\ProgramData\chocolatey\bin
        key: ${{ runner.os }}-choco-${{ hashFiles('**/choco-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-choco-

    - name: Setup Windows dependencies
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        # check cache if restored
        if [ -d "C:\ProgramData\chocolatey\bin" ]; then
          echo "Restored Cache."
        else
          choco install openssl -y
        fi

    - name: Export Keystore Info
      if: matrix.target == 'android'
      run: |
        echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
        echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "KEYSTORE_FILE=release.keystore" >> $GITHUB_ENV
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > release.keystore || { echo "Keystore decoding failed"; exit 1; }

    - name: Make gradlew executable
      if: matrix.target == 'android'
      run: chmod +x ./gradlew

    - name: Build APK with Gradle
      if: matrix.target == 'android'
      run: ./gradlew assembleRelease

    - name: Configure CMake (Linux/Windows)
      if: matrix.target != 'android'
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build (Linux/Windows)
      if: matrix.target != 'android'
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test (Linux/Windows)
      if: matrix.target != 'android'
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}

    - name: Upload APK artifact
      if: matrix.target == 'android'
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: app/build/outputs/apk/release/*.apk

